src/components/main/YoutubeCard/YoutubeCard.style.tsx
src/components/main/YoutubeCard/YoutubeCard.tsx
src/stories/Card/YoutubeCard.stories.tsx

#2 메인페이지 유튜브카드 제작
🪐 작업 내용
- 메인페이지 유튜브 카드 컴포넌트 제작
- 컴포넌트 내에서 사용할 `props` 인터페이스로 구현
- 스타일 요소 입히기
- 스토리북을 통한 컴포넌트 디테일 확인 및 수정
📚 Reference
✅ Check List

feature:  메인페이지 카드 컴포넌트 제작

---

src/components/main/Footer/Footer.style.tsx
src/components/main/Footer/Footer.tsx
src/stories/Footer/Footer.stories.tsx

#7
🪐 작업 내용
Footer UI 구현하였습니다.
📚 Reference
✅ Check List

feature: Footer UI 구현 

---

src/Globalstyle.tsx
src/components/common/Button/RectangleButton/RectangleButton.style.tsx
src/components/common/Button/RectangleButton/RectangleButton.tsx
src/pages/Maintenance/MaintenancePage.style.tsx
src/pages/Maintenance/MaintenancePage.tsx
src/stories/Button/RectangleButton.stories.tsx
src/stories/Page/MaintenancePage.stories.tsx

#16 
🪐 작업 내용
- 아직 개발되지 않은 곳에 접속 시 기능 개발중을 표시하기 위한 메인터넌스 UI를 제작
- 메인터넌스 페이지 storybook 추가
📚 Reference
✅ Check List

feature: 메인터넌스 UI 제작

---

src/components/common/PlaceCard/PlaceCardItem/PlaceCardItem.style.tsx
src/components/common/PlaceCard/PlaceCardItem/PlaceCardItem.tsx
src/components/common/PlaceCard/PlaceCardList/PlaceCardList.style.tsx
src/components/common/PlaceCard/PlaceCardList/PlaceCardList.tsx
src/stories/Card/PlaceCard.stories.tsx
src/stories/Card/PlaceCardList.stories.tsx
src/styles/Theme.ts

#24 
🪐 작업 내용
여행 코스의 장소 카드를 구현하였습니다!
📚 Reference
✅ Check List

feature: travel course card UI 구현

---

package-lock.json
package.json
src/App.tsx
src/pages/MainPage.tsx
src/router/index.tsx

#30 
🪐 작업 내용
createBrowserRouter로 리액트 라우터 돔을 세팅했습니다.
📚 Reference
https://reactrouter.com/6.29.0/start/overview
✅ Check List

feature : 라우팅 세팅

---

src/components/common/GlobalHeader/GlobalHeader.style.tsx
src/components/common/GlobalHeader/GlobalHeader.tsx
src/components/common/Tabs/Tab/Tab.style.tsx
src/components/common/Tabs/TabPanel/TabPanel.style.tsx
src/components/common/TravelMap/TravelMap.style.tsx
src/components/common/TravelMap/TravelMap.tsx
src/components/common/TravelMapMarker/TravelMapMarker.style.tsx
src/components/detail/TravelCourse/TravelCourse.style.tsx
src/components/detail/Video/VideoSection.style.tsx
src/components/detail/Video/VideoSection.tsx
src/components/main/Header/Header.tsx
src/pages/TravelCourse/TravelCoursePage.style.tsx
src/pages/TravelCourse/TravelCoursePage.tsx
src/router/index.tsx
src/stories/Video/VideoSection.stories.tsx

🪐 작업 내용
- 상세 페이지를 위해 제작한 컴포넌트들을 조합하여 상세 페이지를 구현했습니다.
- 기존 figma의 디자인과 최대한 일치시키기 위해 css 스타일을 변경했습니다.
📚 Reference
- 현재 개발된 디자인
- 기존 피그마 디자인
✅ Check List

feature: 상세 페이지 UI 구현

---

src/components/detail/Video/VideoSection.tsx
src/hooks/quries/useGetTravelCourse.tsx
src/mocks/handlers.ts
src/mocks/reslovers.ts
src/pages/TravelCourse/TravelCoursePage.tsx

#34 
🪐 작업 내용
- 상세 페이지 데이터 조회 훅 구현
- 상세 페이지에서 데이터를 받아와 렌더링 되도록 변경
- MSW 에서 PathVariable의 id 값 지정이 안되어 api를 고정시켜 데이터를 가져오는 방식으로 진행
📚 Reference
- 혜정님이 작성한 코드 기반으로 진행했습니다.
✅ Check List

feature: 상세페이지 훅 기능 구현

---

src/stories/Video/VideoSection.stories.tsx

🪐 작업 내용
📚 Reference
✅ Check List

fix: 비디오 스토리북 빌드 시 오류 해결

---

src/components/common/Loading/Loading.style.tsx
src/components/common/Loading/Loading.tsx
src/components/detail/TravelCourse/TravelCourse.tsx
src/constants/index.ts
src/pages/Main/MainPage.style.tsx
src/pages/Main/MainPage.tsx
src/pages/TravelCourse/TravelCoursePage.style.tsx
src/pages/TravelCourse/TravelCoursePage.tsx

#53 
🪐 작업 내용
에러처리 컴포넌트 만들기 
📚 Reference
✅ Check List

feature: 에러 핸들링

---

src/pages/NotFound/NotFoundPage.style.tsx
src/pages/NotFound/NotFoundPage.tsx
src/router/index.tsx

#54 
🪐 작업 내용
📚 Reference
✅ Check List

feature: notfound 페이지 구현 

---

src/components/common/PlaceCard/PlaceCardItem.tsx
src/components/common/Tabs/Tab/Tab.tsx
src/components/common/TravelMap/TravelMap.tsx
src/components/detail/TravelCourse/TravelCourse.tsx
src/components/detail/Video/VideoSection.tsx
src/hooks/quries/useGetTravelCourse.tsx
src/hooks/quries/useGetTravelVideoList.tsx
src/pages/TravelCourse/TravelCoursePage.tsx
src/types/index.ts

🪐 작업 내용
📚 Reference
✅ Check List

feature: api 연결

---

src/hooks/quries/useGetTravelVideoList.tsx
src/stories/Card/PlaceCard.stories.tsx
src/stories/Tab/Tab.stories.tsx
src/stories/TravelCourse/TravelCourse.stories.tsx
src/stories/Video/VideoSection.stories.tsx
src/types/index.ts

🪐 작업 내용
📚 Reference
✅ Check List

fix: 빌드 오류 수정 #57

---

src/components/common/Dropdown/DropdownList/DropdownList.style.tsx
src/components/detail/Video/VideoSection.tsx
src/components/main/SortDropdown/SortDropdown.tsx
src/constants/index.ts
src/hooks/select/useSubmitOption.tsx
src/pages/Main/MainPage.style.tsx
src/pages/Main/MainPage.tsx
src/store/SelectOptionContext.tsx

#62 
🪐 작업 내용
브라우저에 셀렉 옵션 저장
띄어쓰기 수정
애니메이션 수정
📚 Reference
✅ Check List

feature: 셀렉 박스 버그 수정

---

src/hooks/quries/useGetTravelVideoList.tsx
src/store/SelectOptionContext.tsx

#65 
🪐 작업 내용
디폴트 값 서울로 변경 및 여행 지역 검색 파라미터 버그 수정
📚 Reference
✅ Check List

bug : 디폴트 값 서울로 변경 및 여행 지역 검색 파라미터 버그 수정

---

src/Globalstyle.tsx
src/components/common/TravelMap/TravelMap.tsx
src/components/common/TravelMapMarker/TravelMapMarker.style.tsx
src/components/common/TravelMapMarker/TravelMapMarker.tsx
src/styles/Theme.ts

#69 
🪐 작업 내용
- 지도 마커 클릭 시 장소 정보 나오게 설정
- z-index 설정
- 지도 줌 설정 변경
📚 Reference
✅ Check List

feature: 상세 정보 페이지의 맵 설정

---

src/components/main/SortDropdown/SortDropdown.tsx

#81 
🪐 작업 내용
QA 진행 중에 드롭다운 너비로 인해 드롭다운 이외의 화면을 클릭해도 닫히지 않는다는 문제가 있어 수정했습니다!
📚 Reference
✅ Check List

fix: 드롭다운 닫기 문제 해결 

---

src/components/detail/Video/VideoSection.tsx
src/components/main/TravelVideoList/TravelVideoList.tsx
src/components/main/YoutubeCard/YoutubeCard.style.tsx
src/pages/Main/MainPage.tsx

#83 
🪐 작업 내용
메인페이지 깜빡이는 문제 해결하였습니다 !
여행 비디오가 없는 경우와 error가 있는 경우를 `TravelVideoList`컴포넌트 안에서 처리하게 수정하였습니다.
📚 Reference
✅ Check List

refactor: 메인페이지 깜빡이는 문제 해결

---

src/Globalstyle.tsx
src/components/common/GlobalHeader/GlobalHeader.style.tsx
src/components/common/Select/SelectOptionList/SelectOptionList.style.tsx
src/components/common/Select/SelectOptionList/SelectOptionList.tsx
src/components/common/Select/SelectTab/SelectTab.style.tsx
src/components/common/Select/SelectTab/SelectTab.tsx
src/components/common/Select/SelectTrigger/SelectTrigger.tsx
src/components/common/Select/SelectTrigger/selectTrigger.style.tsx
src/components/main/Header/Header.style.tsx
src/components/main/Select/Select.style.tsx
src/components/main/TravelVideoList/TravelVideoList.style.tsx

#93 
🪐 작업 내용
메인페이지 반응형 디자인 적용하기 
📚 Reference
✅ Check List

feature: 메인페이지 반응형 디자인 #93

---

src/components/main/Header/Header.tsx

#97 
🪐 작업 내용
- 메인페이지 헤더 멘트 수정
📚 Reference
✅ Check List

refactor: 헤더 멘트 수정 #97

---

src/Globalstyle.tsx
src/components/main/Footer/Footer.style.tsx
src/components/main/Footer/Footer.tsx

#99 
🪐 작업 내용
- 푸터에 팀소개 및 구글 폼 링크 추가
📚 Reference
✅ Check List

refactor: 푸터에 팀소개 링크 및 구글폼 링크 추가

---

src/Globalstyle.tsx
src/components/common/GlobalHeader/GlobalHeader.tsx
src/components/common/Logo/Logo.tsx
src/components/common/TravelMapMarker/TravelMapMarker.tsx
src/components/main/Header/Header.tsx
src/pages/Maintenance/MaintenancePage.tsx
src/pages/NotFound/NotFoundPage.tsx
src/pages/TravelCourse/TravelCoursePage.tsx
src/stories/Logo/Logo.stories.tsx
src/tests/components/travelcourse/GlobalHeader.test.tsx

#99 
🪐 작업 내용
- 메인페이지 로고 클릭 시 초기화
📚 Reference
✅ Check List

refactor: 디자인 수정 및 문제 해결

---

README.md

update-read.me
🪐 작업 내용
프론트 리드미 작성
📚 Reference
✅ Check List

docs: update-read.me

---

src/components/common/Tabs/TabPanel/TabPanel.style.tsx
src/components/detail/TravelCourse/TravelCourse.style.tsx
src/pages/TravelCourse/TravelCoursePage.style.tsx

#114 
🪐 작업 내용
여행 코스 스크롤 없애고 높이 조정
지도 높이 조정
📚 Reference
✅ Check List

refactor:style travel course responsive

---

src/components/common/Select/SelectOptionList/SelectOptionList.tsx
src/constants/index.ts
src/types/index.ts
src/utils/index.ts

#117
🪐 작업 내용
베트남, 중국 데이터 추가
📚 Reference
✅ Check List

feature: 베트남, 중국 데이터 추가 #117

---

src/components/common/TravelMapMarker/TravelMapMarker.style.tsx
src/components/common/TravelMapMarker/TravelMapMarker.tsx

#119 
🪐 작업 내용
마커 디자인 변경하였습니다. 장소 이름도 추가했어용
📚 Reference
✅ Check List

fix: 마커 스타일 변경 #119

---

src/components/detail/TravelCourse/TravelCourse.style.tsx
src/components/detail/Video/VideoSection.style.tsx
src/components/detail/Video/VideoSection.tsx
src/pages/TravelCourse/TravelCoursePage.style.tsx
src/pages/TravelCourse/TravelCoursePage.tsx

#120 
🪐 작업 내용
- 지도를 비디오 섹션 크기로 줄여 여행코스와 함께 볼 수 있도록 수정
- 모바일에서 지도, 비디오 전환을 탭 버튼을 통해 전환하도록 수정
📚 Reference
✅ Check List

refactor: 상세 페이지 모바일 디자인 변경

---

src/constants/options.ts

#126 
🪐 작업 내용
하노이 지역 상수 값 추가
📚 Reference
✅ Check List

feat: 하노이 지역 상수 값 추가 #126

---

src/components/common/TravelMap/TravelMap.tsx
src/components/common/TravelMapInfoWindow/TravelMapInfoWindow.tsx
src/components/common/TravelMapMarker/TravelMapMarker.tsx

#128 
🪐 작업 내용
구글 지도검색 쿼리 수정
📚 Reference
✅ Check List

fix: 구글 지도검색 쿼리 수정

---

src/App.tsx
src/components/common/Button/RectangleButton/RectangleButton.style.tsx
src/components/common/Button/RectangleButton/RectangleButton.tsx
src/components/common/PlaceCard/PlaceCardItem.style.tsx
src/components/common/PlaceCard/PlaceCardItem.tsx
src/components/common/TravelMap/TravelMap.style.tsx
src/components/common/TravelMapMarker/TravelMapMarker.tsx
src/components/detail/TravelCourseFavorite/FavoriteListSelect.style.tsx
src/components/detail/TravelCourseFavorite/FavoriteListSelect.tsx
src/hooks/context/useSelectFavotieListContext.tsx
src/pages/TravelCourse/TravelCoursePage.style.tsx
src/pages/TravelCourse/TravelCoursePage.tsx
src/store/SelectFavoriteListContext.tsx
src/stories/FavoriteListSelect/FavoriteListSelect.stories.tsx

#133 
🪐 작업 내용
- 하트 버튼 클릭 시 localStorage에 여행 고유 Id 저장
- 하트 버튼 클릭 시 마커 활성화 되는 클릭 이벤트 버블링 방지 설정
- 여행 상세 정보 저장 목록 UI 구현
📚 Reference
- [클릭 이벤트 버블링 방지](https://velog.io/@proshy/JS-%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-%EA%B8%B0%EB%B3%B8-%EC%9D%B4%EB%B2%A4%ED%8A%B8%EC%99%80-%EB%B2%84%EB%B8%94%EB%A7%81-%EB%B0%A9%EC%A7%80)
✅ Check List

feature: 여행 장소 찜하기 기능 및 UI 추가

---

.gemini/config.yaml
.gemini/styleguide.md

#140 
🪐 작업 내용
- Gemini Code Assist 적용
- 행동 맞춤 설정 및 스타일 가이드 작성
📚 Reference
[https://www.notion.so/Github-223a5ac577e98012b6def971792cd06f?source=copy_link](Github 코드 리뷰 봇 도입)
✅ Check List

chore: code review bot 적용
